baseURL = "https://www.awareparenting.es/"
languageCode = "es-es"
paginate		= 5
paginatePath	= "newspage"
canonifyurls	= false
enableRobotsTXT = true

disableKinds = ["taxonomy", "term"]

title = "Laura Díaz de Entresotos - Psicóloga - Aware Parenting en España"
author         	= "Laura Díaz de Entresotos"
copyright		= "© 2020 Laura Díaz de Entresotos. Todos los derechos reservados."

theme        	= "ap_theme"

[Permalinks]
    news = "/news/:year/:month/:day/:filename/"
    
[params]
    favicon = "/static/img/favicon.ico"
    email = "laura@awareparenting.es"
    year = "2019"
    author         	= "Laura Díaz de Entresotos"
    description     = "Psicóloga colegiada con 18 años de experiencia, especializada en psicología infantil y familia. Enfoque basado en la disciplina no punitiva, el respeto y el apego."
    

# Navigation
    [params.navigation]
        brand 		= "Aware Parenting"
        brand_logo	= "/img/ap_logo_full.svg"
        sobremi = "Más  "
			[params.navigation.items]
				[params.navigation.items.001]
					name			= "Consulta"
					url				= "/consulta/"
					frontpageurl	= "/consulta/"
                [params.navigation.items.002]
					name		 	= "Formación"
					url			 	= "/cursos/"
					frontpageurl 	= "/cursos/"
				[params.navigation.items.003]
					name			= "Escuela de Familias Online"
					url				= "/escuela-de-familias/"
					frontpageurl	= "/escuela-de-familias/"
                
            [params.navigation.housekeeping]
                [params.navigation.housekeeping.001]
                    name			= "Sobre Mí"
					url				= "/about/"
					frontpageurl	= "/about/"
                [params.navigation.housekeeping.002]
					name			= "Contacto"
					url				= "/about/#contacto"
					frontpageurl	= "/about/#contacto"
                [params.navigation.housekeeping.003]
					name			= "Aware Parenting"
					url				= "/aware-parenting/"
					frontpageurl	= "/aware-parenting/"   
                [params.navigation.housekeeping.004]
					name			= "Artículos"
					url				= "/articulos/"
					frontpageurl	= "/articulos/" 

 # Hero Section                    
	[params.hero]
        titulo ="Laura Díaz de Entresotos"
        subtitulo ="PSICÓLOGA - INSTRUCTORA AWARE PARENTING"
        texto ="Un enfoque de educación y crianza que **sí** funciona para todos, basado en la disciplina no punitiva, el respeto, y el apego"
        bgimage = "/css/img/hero_bg.jpeg"
        bgimagemobile = "/css/img/hero_bg_mobile.jpeg"
        button_1 = "Consulta"
        button_2 = "Próximos Cursos"
        [params.hero.menu]
            [params.hero.menu.001]
                name    = "Consulta"
                url     = "/consulta/"
                
            [params.hero.menu.002]
                name    = "Escuela de Familias Online"
                url     = "/escuela-de-familias/"
                
            [params.hero.menu.003]
                name    = "Próximos Cursos"
                url     = "#proximoscursos"
                scroll  = "cursos"
            
            

# Features Section            
    [params.features]
        titulo   ="¿Cuáles son las bases de mi enfoque?"
        subtitulo  ="Mi enfoque terapéutico se basa en Aware Parenting, una filosofía de crianza desarrollada por la Dra. Aletha Solter a partir de las investigaciones más recientes acerca del desarrollo infantil. Cuestiona gran parte de las ideas tradicionales acerca de la crianza y propone un nuevo enfoque capaz de transformar las relaciones con nuestros hijos basándose en el respeto y el amor.<br><br>La filosofía de Aware Parenting se sustenta en tres pilares:"
        more    ="¿Quieres saber más?"
        morelink ="/aware-parenting"
        [params.features.items]
            [params.features.items.001]
                name    = "Paternidad basada en el apego"
                img    ="apego_2.svg"
            [params.features.items.002]
                name    = "Disciplina no punitiva"
                img    ="recompensas2.svg"
            [params.features.items.003]
                name    = "Curación del estrés y el trauma"
                img    ="stress_2.svg"
                

# Proximos cursos
    [params.proximoscursos]
        titulo = "Próximos Cursos y Charlas"
        maintext ="Estos son los próximos cursos y charlas programados. Si quieres conocer con más detalle todos los cursos y charlas que ofrezco, haz click en el botón."
        more = "+ info sobre cursos"
        morelink = "/cursos"

# Consulta
    [params.consulta]
        titulo = "Consulta Privada"
        maintext ="Con mas de 15 años de experiencia, ofrezco consultas privadas a padres para ayudarles a mejorar la relación con sus hijos, afrontar conflictos, y resolver los problemas de comportamiento más comunes.<br>También ofrezco orientación a educadores, psicólogos, y otros profesionales que quieran trabajar con el enfoque de Aware Parenting."
        more = "Solicita una consulta ahora"
        morelink = "#contacto"
        [params.consulta.items]
            [params.consulta.items.001]
                name    ="Presencial"
                img     ="consulta_presencial_white.svg"
            [params.consulta.items.002]
                name    ="A distancia"
                img     ="videocall_white.svg"
    

# articulos
    [params.articulos]
        Title = "Artículos"
        readmore = "Leer más"
        prev = "Entradas Recientes"
        next = "Entradas Antiguas"

# Footer
    [params.footer]
        Titlemenu1 = "SITIO"
        Titlemenu2 = "NAVEGACIÓN"
        Titlemenu3 = "ÚLTIMAS ENTRADAS"
        Titlemenu4 = "CONTACTO"
        [params.footer.menu1]
            [params.footer.menu1.001]
                name = "Sitemap"
                url = "/sitemap.xml"
            [params.footer.menu1.002]
                name = "Política de Privacidad y cookies"
                url = "/politica-de-privacidad-y-cookies"
            [params.footer.menu1.004]
                name="Condiciones de uso"
                url="/terms"
        [params.footer.menu4]
            [params.footer.menu4.001]
                name="Laura Díaz de Entresotos"
                url=""
            [params.footer.menu4.002]
                name="e-mail: "
                value ="laura@awareparenting.es"
                url="mailto:laura@awareparenting.es"
            [params.footer.menu4.003]
                name="telefono: "
                value="687 05 45 95"
                url= "tel:+34687054595"
 
# Formularios mensajes:
    [params.form]
        contactoexito ="Gracias por tu mensaje, me pondré en contacto contigo lo antes posible."
        escuelaexito ="Gracias por reservar tu plaza para la escuela de familias. En breve me pondré en contacto contigo para confirmar la plaza."
        inscripcionexito ="¡Muchas gracias! Hemos recibido tu solicitud de inscripción correctamente. En unos minutos enviaremos al email que nos has indicado las instrucciones para completar tu inscripción. Esto debería ser casi instantáneo, así que si no recibes nuestro email pasados unos minutos, por favor revisa la bandeja de SPAM de tu correo electrónico o escríbeme a laura@awareparenting.es"
        faqexito ="Gracias, he recibido tu pregunta. En breve te responderé personalmente."
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = false
  [minify.tdewolff]
    [minify.tdewolff.css]
      decimals = -1
      keepCSS2 = true
    [minify.tdewolff.html]
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
    [minify.tdewolff.json]
    [minify.tdewolff.svg]
      decimals = -1
    [minify.tdewolff.xml]
      keepWhitespace = false
 
 
 
 
 
 
 
 
 

